#@ load("@ytt:data", "data")

#! From: https://github.com/mittwald/kubernetes-replicator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-synchronizer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-synchronizer
roleRef:
  kind: ClusterRole
  name: secret-synchronizer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: secret-synchronizer
    namespace: #@ data.values.ingress.namespace
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: secret-synchronizer
  namespace: #@ data.values.ingress.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-synchronizer
  namespace: #@ data.values.registry.namespace
spec:
  selector:
    matchLabels:
      app: secret-synchronizer
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: secret-synchronizer
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: secret-synchronizer
          image: quay.io/mittwald/kubernetes-replicator:v2.3.0
          imagePullPolicy: IfNotPresent
      serviceAccountName: secret-synchronizer
