#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pull-secret-copier
  namespace: #@ data.values.registry.namespace
imagePullSecrets:
  - name: #@ "{}-creds".format(data.values.registry.name)
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pull-secret-copier
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pull-secret-copier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-copier
subjects:
  - kind: ServiceAccount
    name: pull-secret-copier
    namespace: #@ data.values.registry.namespace
---
#@ if data.values.privileged_clusterrole_name:
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pull-secret-copier-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ data.values.privileged_clusterrole_name
subjects:
  - kind: ServiceAccount
    name: pull-secret-copier
    namespace: tanzu-developer
#@ end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-secret-copier
  namespace: #@ data.values.registry.namespace
  labels: 
    app: pull-secret-copier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pull-secret-copier
  template:
    metadata:
      labels:
        app: pull-secret-copier
    spec:
      containers:
      - name: pull-secret-copier
        image: quay.io/jorgemoralespou/image-puller-secret-operator:latest
        env:
        - name: MAIN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        imagePullPolicy: IfNotPresent
      serviceAccountName: pull-secret-copier
