apiVersion: v1
kind: Namespace
metadata:
  name: eduk8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eduk8s-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: eduk8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eduk8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduk8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: eduk8s-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: eduk8s-operator
    spec:
      serviceAccountName: eduk8s
      containers:
      - name: eduk8s
        image: quay.io/eduk8s/eduk8s-operator:develop
        imagePullPolicy: Always
---